name: RegulusDataSetter
version: "0.0.2"
slug: regulus_data_setter
description: Run a Python script as a Home Assistant add-on
url: https://github.com/hajekmartin/regulusdatasetter
arch:
    - armhf
    - armv7
    - amd64
    - aarch64
init: false
options:
  guid: ''
  url: ''
schema:
  guid: str
  url: str
logger:
  default: info
system_log:
  max_entries: MAX_ENTRIES
