name: RegulusDataReader
version: "0.0.2"
slug: regulus_data_reader
description: Run a Python script as a Home Assistant add-on
url: https://github.com/hajekmartin/regulusdatareader
arch:
    - armhf
    - armv7
    - amd64
    - aarch64
init: false
logger:
  default: info
system_log:
  max_entries: MAX_ENTRIES
